<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class NavigationMenusSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('navigation_menus')->insert([
            [
                'id'         => 1,
                'name'       => 'Dashboard',
                'roles'      => 'owner, eo, manager',
                'route'      => null,
                'parent_id'  => null,
                'sort_order' => 1,
                'created_by' => 'admin',
                'created_at' => '2025-01-04 10:51:45',
                'updated_at' => '2025-01-05 06:52:59',
            ],
            [
                'id'         => 2,
                'name'       => 'Master',
                'roles'      => 'owner, admin',
                'route'      => '#',
                'parent_id'  => null,
                'sort_order' => 2,
                'created_by' => 'admin',
                'created_at' => '2025-01-04 10:53:48',
                'updated_at' => '2025-01-04 10:53:48',
            ],
            [
                'id'         => 3,
                'name'       => 'Teams',
                'roles'      => 'owner, manager',
                'route'      => 'teams',
                'parent_id'  => null,
                'sort_order' => 3,
                'created_by' => 'admin',
                'created_at' => '2025-01-04 10:54:25',
                'updated_at' => '2025-01-04 10:54:25',
            ],
            [
                'id'         => 5,
                'name'       => 'Match Settings',
                'roles'      => 'owner',
                'route'      => '#',
                'parent_id'  => null,
                'sort_order' => 5,
                'created_by' => 'admin',
                'created_at' => '2025-01-05 06:44:09',
                'updated_at' => '2025-01-05 06:44:09',
            ],
            [
                'id'         => 6,
                'name'       => 'Team Members',
                'roles'      => 'user, owner, manager',
                'route'      => 'team-members',
                'parent_id'  => null,
                'sort_order' => 6,
                'created_by' => 'public',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 7,
                'name'       => 'Payment',
                'roles'      => 'owner, manager, user',
                'route'      => 'payment',
                'parent_id'  => null,
                'sort_order' => 7,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 8,
                'name'       => 'Classes',
                'roles'      => 'owner, admin',
                'route'      => 'classes',
                'parent_id'  => 2,
                'sort_order' => 1,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 9,
                'name'       => 'Match Clasification',
                'roles'      => 'owner, admin',
                'route'      => 'match-clasification',
                'parent_id'  => 14,
                'sort_order' => 1,
                'created_by' => 'public',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 10,
                'name'       => 'Tanding',
                'roles'      => 'owner, admin',
                'route'      => 'tanding',
                'parent_id'  => 5,
                'sort_order' => 2,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 12,
                'name'       => 'System Settings',
                'roles'      => 'owner',
                'route'      => '#',
                'parent_id'  => null,
                'sort_order' => 6,
                'created_by' => 'admin',
                'created_at' => '2025-03-28 13:43:53',
                'updated_at' => '2025-03-28 13:43:53',
            ],
            [
                'id'         => 13,
                'name'       => 'Navigation',
                'roles'      => 'owner, admin',
                'route'      => 'navigation',
                'parent_id'  => 12,
                'sort_order' => 1,
                'created_by' => 'admin',
                'created_at' => '2025-03-28 13:45:39',
                'updated_at' => '2025-03-28 13:45:39',
            ],
            [
                'id'         => 14,
                'name'       => 'Tournament Settings',
                'roles'      => 'owner, eo',
                'route'      => '#',
                'parent_id'  => null,
                'sort_order' => 8,
                'created_by' => 'admin',
                'created_at' => '2025-04-07 13:24:17',
                'updated_at' => '2025-04-07 13:24:17',
            ],
            [
                'id'         => 15,
                'name'       => 'Tournament',
                'roles'      => 'owner, admin, eo',
                'route'      => 'tournament',
                'parent_id'  => 14,
                'sort_order' => 1,
                'created_by' => 'admin',
                'created_at' => '2025-04-07 13:29:01',
                'updated_at' => '2025-04-07 13:29:01',
            ],
            [
                'id'         => 18,
                'name'       => 'Tournament Category',
                'roles'      => 'owner, admin',
                'route'      => 'tournament-category',
                'parent_id'  => 14,
                'sort_order' => 2,
                'created_by' => 'admin',
                'created_at' => '2025-04-08 07:18:49',
                'updated_at' => '2025-04-08 07:18:49',
            ],
            [
                'id'         => 19,
                'name'       => 'Tournament Activity',
                'roles'      => 'owner, admin, eo',
                'route'      => 'tournament-activity',
                'parent_id'  => 14,
                'sort_order' => 3,
                'created_by' => 'public',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 20,
                'name'       => 'Contact Person',
                'roles'      => 'owner, admin, eo',
                'route'      => 'contact-person',
                'parent_id'  => 14,
                'sort_order' => 4,
                'created_by' => 'admin',
                'created_at' => '2025-04-13 08:53:20',
                'updated_at' => '2025-04-13 08:53:20',
            ],
            [
                'id'         => 21,
                'name'       => 'Tournament Arena',
                'roles'      => 'owner, admin, eo',
                'route'      => 'tournament-arena',
                'parent_id'  => 14,
                'sort_order' => 5,
                'created_by' => 'admin',
                'created_at' => '2025-04-13 08:53:48',
                'updated_at' => '2025-04-13 08:53:48',
            ],
            [
                'id'         => 22,
                'name'       => 'Tournament Schedule',
                'roles'      => 'owner, admin, eo',
                'route'      => 'tournament-schedule',
                'parent_id'  => 14,
                'sort_order' => 7,
                'created_by' => 'admin',
                'created_at' => '2025-04-13 21:23:23',
                'updated_at' => '2025-04-13 21:23:23',
            ],
            [
                'id'         => 23,
                'name'       => 'Seni',
                'roles'      => 'owner, admin',
                'route'      => 'seni',
                'parent_id'  => 5,
                'sort_order' => 2,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id'         => 24,
                'name'       => 'Blogs',
                'roles'      => '',
                'route'      => 'blogs',
                'parent_id'  => 2,
                'sort_order' => 2,
                'created_by' => 'admin',
                'created_at' => '2025-12-02 02:23:46',
                'updated_at' => '2025-12-02 02:24:20',
            ],
        ]);
    }
}
